// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVHEr_SaLjxH_qX0fRr1zf9VGcyAXzD1k',
    appId: '1:264893986080:web:4a4dfddbada30104aa9345',
    messagingSenderId: '264893986080',
    projectId: 'recycling-86931',
    authDomain: 'recycling-86931.firebaseapp.com',
    storageBucket: 'recycling-86931.appspot.com',
    measurementId: 'G-LPEGKDKHE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCohu9fpXPsd8psXQEeY0gMNMhrlbsuM_Q',
    appId: '1:264893986080:android:ec4744f6be97b966aa9345',
    messagingSenderId: '264893986080',
    projectId: 'recycling-86931',
    storageBucket: 'recycling-86931.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFFKUoFKXwp3_sKfb6cMolmp-29zYMB_w',
    appId: '1:264893986080:ios:fb4b9ecafbc9058daa9345',
    messagingSenderId: '264893986080',
    projectId: 'recycling-86931',
    storageBucket: 'recycling-86931.appspot.com',
    iosBundleId: 'com.example.payt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFFKUoFKXwp3_sKfb6cMolmp-29zYMB_w',
    appId: '1:264893986080:ios:fb4b9ecafbc9058daa9345',
    messagingSenderId: '264893986080',
    projectId: 'recycling-86931',
    storageBucket: 'recycling-86931.appspot.com',
    iosBundleId: 'com.example.payt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVHEr_SaLjxH_qX0fRr1zf9VGcyAXzD1k',
    appId: '1:264893986080:web:3542fdc5d5c74d83aa9345',
    messagingSenderId: '264893986080',
    projectId: 'recycling-86931',
    authDomain: 'recycling-86931.firebaseapp.com',
    storageBucket: 'recycling-86931.appspot.com',
    measurementId: 'G-BMTSKD9XXK',
  );
}
